# This file was automatically generated by vpl
foreach impl_run $impl_runs {
  add_files -fileset utils_1 -norecurse scripts/$impl_run/_full_init_post.tcl
  set_property -name STEPS.INIT_DESIGN.TCL.POST -value [get_files -of_object [get_filesets utils_1] scripts/$impl_run/_full_init_post.tcl] -objects $impl_run
  add_files -fileset utils_1 -norecurse scripts/$impl_run/_full_init_pre.tcl
  set_property -name STEPS.INIT_DESIGN.TCL.PRE -value [get_files -of_object [get_filesets utils_1] scripts/$impl_run/_full_init_pre.tcl] -objects $impl_run
  add_files -fileset utils_1 -norecurse scripts/$impl_run/_full_opt_post.tcl
  set_property -name STEPS.OPT_DESIGN.TCL.POST -value [get_files -of_object [get_filesets utils_1] scripts/$impl_run/_full_opt_post.tcl] -objects $impl_run
  add_files -fileset utils_1 -norecurse scripts/$impl_run/_full_opt_pre.tcl
  set_property -name STEPS.OPT_DESIGN.TCL.PRE -value [get_files -of_object [get_filesets utils_1] scripts/$impl_run/_full_opt_pre.tcl] -objects $impl_run
  add_files -fileset utils_1 -norecurse scripts/$impl_run/_full_place_post.tcl
  set_property -name STEPS.PLACE_DESIGN.TCL.POST -value [get_files -of_object [get_filesets utils_1] scripts/$impl_run/_full_place_post.tcl] -objects $impl_run
  add_files -fileset utils_1 -norecurse scripts/$impl_run/_full_place_pre.tcl
  set_property -name STEPS.PLACE_DESIGN.TCL.PRE -value [get_files -of_object [get_filesets utils_1] scripts/$impl_run/_full_place_pre.tcl] -objects $impl_run
  add_files -fileset utils_1 -norecurse scripts/$impl_run/_full_post_route_phys_opt_post.tcl
  set_property -name STEPS.POST_ROUTE_PHYS_OPT_DESIGN.TCL.POST -value [get_files -of_object [get_filesets utils_1] scripts/$impl_run/_full_post_route_phys_opt_post.tcl] -objects $impl_run
  add_files -fileset utils_1 -norecurse scripts/$impl_run/_full_route_post.tcl
  set_property -name STEPS.ROUTE_DESIGN.TCL.POST -value [get_files -of_object [get_filesets utils_1] scripts/$impl_run/_full_route_post.tcl] -objects $impl_run
  add_files -fileset utils_1 -norecurse scripts/$impl_run/_full_write_device_image_post.tcl
  if {[lsearch [list_property [get_runs $impl_run]] STEPS.WRITE_DEVICE_IMAGE.TCL.POST] != -1} {
  set_property -name STEPS.WRITE_DEVICE_IMAGE.TCL.POST -value [get_files -of_object [get_filesets utils_1] scripts/$impl_run/_full_write_device_image_post.tcl] -objects $impl_run
  } else {
    puts "WARNING: The specified property is not applicable for current platform: 'STEPS.WRITE_DEVICE_IMAGE.TCL.POST', the tcl hook setting for this property is ignored"
  }
  add_files -fileset utils_1 -norecurse scripts/$impl_run/_full_write_device_image_pre.tcl
  if {[lsearch [list_property [get_runs $impl_run]] STEPS.WRITE_DEVICE_IMAGE.TCL.PRE] != -1} {
  set_property -name STEPS.WRITE_DEVICE_IMAGE.TCL.PRE -value [get_files -of_object [get_filesets utils_1] scripts/$impl_run/_full_write_device_image_pre.tcl] -objects $impl_run
  } else {
    puts "WARNING: The specified property is not applicable for current platform: 'STEPS.WRITE_DEVICE_IMAGE.TCL.PRE', the tcl hook setting for this property is ignored"
  }
}
